# Generated by Django 5.1 on 2024-09-12 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=150, verbose_name='Город')),
                ('address', models.TextField(blank=True, max_length=300, verbose_name='Адрес')),
                ('date_delivery', models.DateField(blank=True, verbose_name='Дата доставки')),
                ('time_delivery', models.TimeField(blank=True, verbose_name='Время доставки')),
                ('customer', models.CharField(blank=True, max_length=150, verbose_name='Заказчики')),
                ('comment', models.TextField(blank=True, max_length=200, null=True, verbose_name='Комментарий')),
                ('package', models.CharField(blank=True, choices=[('Letter', 'Письмо'), ('Parcel', 'Бандероль'), ('Overall cargo', 'Габаритный груз')], max_length=20, verbose_name='Тип посылки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
