# Generated by Django 5.1 on 2024-09-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='orders',
            name='status_order',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('In progress', 'In progress'), ('Handed to courier', 'Handed to courier'), ('Done', 'Done'), ('Cancelled', 'Cancelled')], max_length=25, verbose_name='Статус посылки'),
        ),
    ]
